// ============================================================
// Firefly Platform Config Schema
// ============================================================
const FIREFLY_CONFIG_SCHEMA = {
  siteConfig: C("src/config/siteConfig.ts", "网站核心配置：标题、域名、描述、主题色、功能开关等", "站点配置", [
    F.txt("title", "站点标题", { section: "basic", desc: "显示在浏览器标签页和页头的网站名称" }),
    F.txt("subtitle", "副标题", { section: "basic", desc: "标题下方的简短描述语" }),
    F.txt("site_url", "站点URL", { section: "basic", desc: "网站的完整域名" }),
    F.area("description", "站点描述", { section: "basic", desc: "SEO 站点描述" }),
    F.date("siteStartDate", "站点起始日期", { section: "basic", desc: "用于计算站点运行天数" }),
    F.sel("timezone", "时区", ["Asia/Shanghai","UTC","America/New_York","Europe/London","Asia/Tokyo"], { section: "basic" }),
    F.sel("lang", "语言", ["zh_CN","zh_TW","en","ja","ru"], { section: "basic" }),
    F.num("pageWidth", "页面宽度(rem)", { min: 60, max: 160, section: "layout" }),
    F.chk("categoryBar", "分类导航条", { section: "layout" }),
    F.chk("foldArticle", "折叠旧年份文章", { section: "layout" }),
    F.range("themeColor.hue", "主题色相(0-360)", 0, 360, { section: "theme" }),
    F.chk("themeColor.fixed", "固定主题色", { section: "theme" }),
    F.sel("themeColor.defaultMode", "默认模式", ["light","dark","system"], { section: "theme" }),
    F.chk("card.border", "卡片边框", { section: "ui" }),
    F.chk("card.followTheme", "卡片跟随主题色", { section: "ui" }),
    F.chk("pages.friends", "友链页面", { section: "features", group: "pages" }),
    F.chk("pages.sponsor", "打赏页面", { section: "features", group: "pages" }),
    F.chk("pages.guestbook", "留言板页面", { section: "features", group: "pages" }),
    F.chk("pages.bangumi", "番组计划页面", { section: "features", group: "pages" }),
    F.chk("pages.gallery", "相册页面", { section: "features", group: "pages" }),
    F.chk("pages.anime", "追番页面", { section: "features", group: "pages" }),
    F.sel("navbar.logo.type", "Logo类型", ["icon","image","url"], { section: "navbar" }),
    F.txt("navbar.logo.value", "Logo/图标", { section: "navbar" }),
    F.txt("navbar.logo.alt", "Logo替代文字", { section: "navbar" }),
    F.txt("navbar.title", "导航栏标题", { section: "navbar" }),
    F.chk("navbar.widthFull", "全宽导航栏", { section: "navbar" }),
    F.sel("navbar.menuAlign", "菜单对齐", ["left","center"], { section: "navbar" }),
    F.chk("navbar.followTheme", "跟随主题色", { section: "navbar" }),
    F.chk("navbar.stickyNavbar", "固定导航栏", { section: "navbar" }),
    F.chk("post.showLastModified", "显示最后编辑时间", { section: "post" }),
    F.num("post.outdatedThreshold", "过期阈值(天)", { min: 1, section: "post" }),
    F.chk("post.sharePoster", "分享海报", { section: "post" }),
    F.chk("post.generateOgImages", "生成OG图片", { section: "post" }),
    F.sel("post.rehypeCallouts.theme", "提醒框主题", ["github","obsidian","vitepress","docusaurus"], { section: "post" }),
    F.chk("post.rehypeCallouts.enablePythonMarkdownAdmonitions", "兼容Python-Markdown语法", { section: "post" }),
    F.sel("postListLayout.defaultMode", "默认布局", ["list","grid"], { section: "layout" }),
    F.sel("postListLayout.mobileDefaultMode", "移动端默认布局", ["list","grid"], { section: "layout" }),
    F.chk("postListLayout.showTags", "显示标签", { section: "layout" }),
    F.num("postListLayout.tagCount", "标签数量", { min: 0, section: "layout" }),
    F.num("postListLayout.descriptionLines", "简介行数", { min: 0, section: "layout" }),
    F.chk("postListLayout.showStatsIcons", "统计图标", { section: "layout" }),
    F.chk("postListLayout.allowSwitch", "允许切换布局", { section: "layout" }),
    F.chk("postListLayout.grid.masonry", "瀑布流布局", { section: "layout" }),
    F.num("postListLayout.grid.columnWidth", "网格列宽(px)", { min: 200, section: "layout" }),
    F.num("pagination.postsPerPage", "每页文章数", { min: 1, section: "layout" }),
    F.txt("bangumi.userId", "Bangumi用户ID", { section: "integrations" }),
    F.sel("bangumi.mode", "Bangumi模式", ["static","dynamic"], { section: "integrations" }),
    F.txt("bangumi.apiUrl", "Bangumi API", { section: "integrations" }),
    F.txt("anime.bilibili.uid", "Bilibili UID", { section: "integrations" }),
    F.sel("imageOptimization.formats", "图片格式", ["webp","avif","both"], { section: "image" }),
    F.num("imageOptimization.quality", "图片质量", { min: 1, max: 100, section: "image" }),
  ]),

  pioConfig: CS("src/config/pioConfig.ts", "看板娘：Spine和Live2D角色配置", "看板娘", [
    F.chk("spine.enable", "Spine开关"),
    F.txt("spine.modelPath", "Spine模型路径"),
    F.num("spine.scale", "缩放", { min: 0.1, max: 5, step: 0.1 }),
    F.num("spine.x", "X偏移"),
    F.num("spine.y", "Y偏移"),
    F.sel("spine.positionCorner", "位置", ["bottom-left","bottom-right","top-left","top-right"]),
    F.num("spine.width", "容器宽度", { min: 50 }),
    F.num("spine.height", "容器高度", { min: 50 }),
    F.num("spine.zIndex", "层级"),
    F.num("spine.opacity", "不透明度", { min: 0, max: 1, step: 0.05 }),
    F.chk("spine.hideOnMobile", "移动端隐藏"),
    F.chk("live2d.enable", "Live2D开关"),
    F.sel("live2d.position", "L2D位置", ["bottom-left","bottom-right"]),
    F.num("live2d.sizeWidth", "L2D画布宽度", { min: 50 }),
    F.num("live2d.sizeHeight", "L2D画布高度", { min: 50 }),
    F.chk("live2d.hideOnMobile", "L2D移动端隐藏"),
  ], {
    splitExports: true,
    exports: [
      { exportName: "spineModelConfig", typeName: "SpineModelConfig", label: "Spine看板娘" },
      { exportName: "live2dWidgetConfig", typeName: "Live2DWidgetConfig", label: "Live2D看板娘" },
    ],
  }),

  profileConfig: CA("src/config/profileConfig.ts", "个人信息：头像、昵称、个人简介和社交链接", "个人资料", [
    F.img("avatar", "头像路径", "public/images", { desc: "public 目录下的相对路径" }),
    F.txt("name", "昵称", { desc: "显示在页面中的用户名称" }),
    F.area("bio", "个人简介", { desc: "简短的个人介绍" }),
  ], A("links", "社交链接", [
    F.txt("name", "名称", { placeholder: "GitHub", sizeClass: "field-m" }),
    F.txt("url", "链接", { placeholder: "https://...", sizeClass: "field-m" }),
    F.txt("icon", "图标", { placeholder: "fa7-brands:github", sizeClass: "field-m" }),
    F.chk("showName", "显示名称", { sizeClass: "field-n" }),
  ])),

  navBarConfig: CA("src/config/navBarConfig.ts", "导航菜单配置：自定义网站顶部导航栏", "导航栏", [], A("links", "导航链接", [
    F.txt("name", "名称", { labelShort: "名", placeholder: "菜单名称", sizeClass: "field-m" }),
    F.txt("url", "链接", { labelShort: "链", placeholder: "/path/ 或 https://...", sizeClass: "field-m" }),
    F.txt("icon", "图标", { labelShort: "图", placeholder: "material-symbols:home", sizeClass: "field-m" }),
    F.chk("external", "外链", { labelShort: "外" }),
    F.txt("pageKey", "页面Key", { labelShort: "页", sizeClass: "field-s" }),
  ], {
    childrenKey: "children",
    linkPresets: ["Home","Archive","Categories","Tags","Friends","Sponsor","Guestbook","About","Bangumi","Gallery","Anime"],
  })),

  sidebarLayoutConfig: CAL("src/config/sidebarConfig.ts", "侧边栏布局：控制左右侧边栏的组件和显示", "侧边栏布局", [
    F.chk("enable", "启用侧边栏"),
    F.sel("position", "位置", ["left","right","both"]),
    F.sel("tabletSidebar", "平板端侧栏", ["left","right"]),
    F.chk("hideSidebarOnPostPage", "文章页隐藏侧栏"),
    F.chk("showBothSidebarsOnPostPage", "文章页双栏"),
  ], [
    A("leftComponents", "左侧边栏组件 (leftComponents)", [
      F.sel("type", "类型", ["profile","announcement","music","categories","tags","stats","siteInfo","calendar","sidebarToc","advertisement"], { labelShort: "类型", sizeClass: "field-m" }),
      F.chk("enable", "启用", { labelShort: "启" }),
      F.sel("position", "位置", ["top","sticky"], { labelShort: "位", sizeClass: "field-s" }),
      F.chk("showOnPostPage", "文章页显示", { labelShort: "文章" }),
      F.chk("showTitle", "显示标题", { labelShort: "标题" }),
      F.chk("hideOnNonPostPage", "非文章页隐藏", { labelShort: "隐藏" }),
    ]),
    A("rightComponents", "右侧边栏组件 (rightComponents)", [
      F.sel("type", "类型", ["profile","announcement","music","categories","tags","stats","siteInfo","calendar","sidebarToc","advertisement"], { labelShort: "类型", sizeClass: "field-m" }),
      F.chk("enable", "启用", { labelShort: "启" }),
      F.sel("position", "位置", ["top","sticky"], { labelShort: "位", sizeClass: "field-s" }),
      F.chk("showOnPostPage", "文章页显示", { labelShort: "文章" }),
      F.chk("showTitle", "显示标题", { labelShort: "标题" }),
      F.chk("hideOnNonPostPage", "非文章页隐藏", { labelShort: "隐藏" }),
    ]),
    A("mobileBottomComponents", "移动端组件 (mobileBottomComponents)", [
      F.sel("type", "类型", ["profile","announcement","music","categories","tags","stats","siteInfo","calendar","sidebarToc","advertisement"], { labelShort: "类型", sizeClass: "field-m" }),
      F.chk("enable", "启用", { labelShort: "启" }),
      F.chk("showOnPostPage", "文章页显示", { labelShort: "文章" }),
      F.chk("showTitle", "显示标题", { labelShort: "标题" }),
    ]),
  ]),

  commentConfig: C("src/config/commentConfig.ts", "评论系统：配置评论服务", "评论系统", [
    F.chk("enable", "启用评论"),
    F.sel("system", "评论系统", ["twikoo","giscus"]),
    F.txt("twikoo.envId", "Twikoo环境ID"),
    F.txt("twikoo.lang", "Twikoo语言"),
    F.txt("giscus.repo", "Giscus仓库"),
    F.txt("giscus.repoId", "Giscus仓库ID"),
    F.txt("giscus.category", "Giscus分类"),
    F.txt("giscus.categoryId", "Giscus分类ID"),
    F.txt("giscus.mapping", "映射方式"),
    F.txt("giscus.theme", "Giscus主题"),
  ]),

  licenseConfig: C("src/config/licenseConfig.ts", "许可证：网站内容许可协议和版权声明", "许可证", [
    F.chk("enable", "启用许可证"),
    F.txt("name", "许可证名称"),
    F.txt("url", "许可证URL"),
  ]),

  footerConfig: C("src/config/footerConfig.ts", "页脚配置：自定义网站底部信息", "页脚", [
    F.chk("enable", "启用页脚HTML"),
    F.area("customHtml", "自定义HTML"),
  ]),

  announcementConfig: C("src/config/announcementConfig.ts", "公告栏：网站顶部公告横幅", "公告栏", [
    F.txt("title", "公告标题"),
    F.area("content", "公告内容"),
    F.chk("closable", "允许关闭"),
    F.chk("link.enable", "启用链接"),
    F.txt("link.text", "链接文字"),
    F.txt("link.url", "链接URL"),
    F.chk("link.external", "外部链接"),
  ]),

  musicPlayerConfig: C("src/config/musicConfig.ts", "音乐播放器：背景音乐播放", "音乐播放器", [
    F.chk("enable", "启用音乐"),
    F.chk("showInNavbar", "导航栏显示"),
    F.chk("showFloatingPlayer", "悬浮播放器"),
    F.sel("floatingEntryMode", "悬浮入口模式", ["default","fab"]),
    F.sel("mode", "播放器模式", ["local","meting"]),
    F.txt("id", "歌单ID"),
    F.sel("server", "音乐源", ["netease","tencent","kugou","xiami","baidu"]),
    F.sel("type", "播单类型", ["playlist","album","song"]),
  ]),

  fullscreenWallpaperConfig: C("src/config/backgroundWallpaper.ts", "全屏壁纸：背景图片轮播效果", "全屏壁纸", [
    F.chk("enable", "启用壁纸"),
    F.sel("mode", "壁纸模式", ["banner","fullscreen","overlay","none"]),
    F.chk("switchable", "用户可切换"),
    F.chk("playerEnable", "启用视频播放器"),
    F.num("common.dimOpacity", "背景遮罩不透明度", { min: 0, max: 1, step: 0.05 }),
    F.sel("common.playerMode", "视频播放模式", ["random","sequential","single"]),
    F.chk("common.homeText.enable", "启用主页文字"),
    F.chk("common.homeText.switchable", "文字可切换"),
    F.txt("common.homeText.title", "主页标题"),
    F.txt("common.homeText.titleSize", "标题字号", { placeholder: "3.8rem" }),
    F.txt("common.homeText.subtitleSize", "副标题字号", { placeholder: "1.5rem" }),
    F.chk("common.homeText.typewriter.enable", "打字机效果"),
    F.num("common.homeText.typewriter.speed", "打字速度(ms)", { min: 10 }),
    F.num("common.homeText.typewriter.deleteSpeed", "删除速度(ms)", { min: 10 }),
    F.num("common.homeText.typewriter.pauseTime", "暂停时间(ms)", { min: 100 }),
    F.sel("common.navbar.transparentMode", "导航栏透明模式", ["solid","semi","transparent"]),
    F.chk("common.navbar.enableBlur", "导航栏模糊"),
    F.num("common.navbar.blur", "导航栏模糊(px)", { min: 0 }),
    F.chk("common.waves.enable.desktop", "桌面端波浪"),
    F.chk("common.waves.enable.mobile", "移动端波浪"),
    F.chk("common.waves.switchable", "波浪可切换"),
    F.chk("common.gradient.enable.desktop", "桌面端渐变"),
    F.chk("common.gradient.enable.mobile", "移动端渐变"),
    F.txt("common.gradient.height", "渐变高度", { placeholder: "10%" }),
    F.chk("common.gradient.switchable", "渐变可切换"),
    F.chk("common.carousel.enable", "通用轮播"),
    F.num("common.carousel.interval", "通用轮播间隔(ms)", { min: 1000, step: 500 }),
    F.sel("common.carousel.transitionEffect", "过渡效果", ["fade","zoom","slide"]),
    F.chk("common.carousel.switchable", "轮播可切换"),
    F.txt("banner.position", "Banner位置", { placeholder: "0% 20%" }),
    F.num("overlay.zIndex", "覆盖层层级"),
    F.num("overlay.opacity", "覆盖层不透明度", { min: 0, max: 1, step: 0.05 }),
    F.num("overlay.blur", "覆盖层模糊(px)", { min: 0 }),
    F.num("overlay.cardOpacity", "卡片不透明度", { min: 0, max: 1, step: 0.05 }),
    F.chk("overlay.switchable.opacity", "可切换不透明度"),
    F.chk("overlay.switchable.blur", "可切换模糊"),
    F.chk("overlay.switchable.cardOpacity", "可切换卡片不透明度"),
    F.txt("fullscreen.position", "全屏位置", { placeholder: "center" }),
  ]),

  sakuraConfig: C("src/config/effectsConfig.ts", "樱花特效：飘落花瓣动画", "樱花特效", [
    F.chk("enable", "启用樱花"),
    F.chk("switchable", "可切换"),
    F.num("sakuraNum", "樱花数量", { min: 1 }),
    F.num("limitTimes", "限制次数"),
    F.num("size.min", "最小尺寸", { min: 0, step: 0.1 }),
    F.num("size.max", "最大尺寸", { min: 0, step: 0.1 }),
    F.num("opacity.min", "最小不透明度", { min: 0, max: 1, step: 0.05 }),
    F.num("opacity.max", "最大不透明度", { min: 0, max: 1, step: 0.05 }),
    F.num("zIndex", "层级"),
  ]),

  expressiveCodeConfig: C("src/config/expressiveCodeConfig.ts", "代码块样式：代码高亮主题", "代码块样式", [
    F.sel("theme", "代码主题", ["github-dark","github-light","monokai","dracula"]),
    F.chk("hideDuringThemeTransition", "主题切换时隐藏"),
  ]),

  sponsorConfig: C("src/config/sponsorConfig.ts", "打赏页面：收款二维码配置", "打赏页面", [
    F.chk("enable", "启用打赏"),
    F.txt("title", "标题"),
    F.area("description", "描述"),
    F.txt("wechatpay", "微信支付二维码"),
    F.txt("alipay", "支付宝二维码"),
  ]),

  plantumlConfig: C("src/config/plantumlConfig.ts", "PlantUML：图表渲染配置", "PlantUML", [
    F.chk("enable", "启用PlantUML"),
    F.txt("server", "服务器地址"),
  ]),

  galleryConfig: CA("src/config/galleryConfig.ts", "相册：图片展示页面配置，管理多个相册及其图片", "相册", [
    F.chk("enable", "启用相册"),
    F.txt("title", "页面标题"),
    F.num("columnWidth", "列宽(px)", { min: 120, max: 600 }),
  ], A("albums", "相册列表", [
    F.txt("id", "ID", { labelShort: "ID", placeholder: "album-id", sizeClass: "field-m" }),
    F.txt("name", "名称", { labelShort: "名", placeholder: "相册名称", sizeClass: "field-m" }),
    F.txt("description", "描述", { labelShort: "描", placeholder: "相册描述", sizeClass: "field-l" }),
    F.txt("location", "地点", { labelShort: "地", placeholder: "拍摄地点", sizeClass: "field-m" }),
    F.txt("date", "日期", { labelShort: "日", placeholder: "2026-01-01", sizeClass: "field-m" }),
    F.txt("tags", "标签(逗号分隔)", { labelShort: "签", placeholder: "标签1, 标签2", sizeClass: "field-l" }),
    F.txt("cover", "封面图路径", { labelShort: "封", placeholder: "/images/gallery/cover.jpg", sizeClass: "field-l" }),
    F.txt("password", "访问密码", { labelShort: "密", placeholder: "留空则不加密", sizeClass: "field-m" }),
    F.txt("passwordHint", "密码提示", { labelShort: "示", placeholder: "密码提示文字", sizeClass: "field-m" }),
  ])),

  friendsConfig: CA("src/config/friendsConfig.ts", "友链：友链页面内容和申请规则，管理友情链接列表", "友链配置", [
    F.txt("title", "页面标题"),
    F.area("description", "页面描述"),
    F.chk("showCustomContent", "显示自定义内容", { desc: "在友链列表上方显示自定义HTML内容" }),
    F.chk("showComment", "显示评论区", { desc: "在友链页面底部显示评论" }),
    F.chk("randomizeSort", "随机排序", { desc: "每次加载时随机排列友链顺序" }),
  ], A("friends", "友链列表", [
    F.txt("title", "名称", { labelShort: "名", placeholder: "站点名称", sizeClass: "field-m" }),
    F.txt("siteurl", "链接", { labelShort: "链", placeholder: "https://...", sizeClass: "field-m" }),
    F.img("imgurl", "头像", undefined, { placeholder: "https://.../avatar.png", sizeClass: "field-m" }),
    F.txt("desc", "描述", { labelShort: "描", placeholder: "站点简介", sizeClass: "field-l" }),
    F.txt("tags", "标签 (,分隔)", { labelShort: "标", placeholder: "技术,生活", sizeClass: "field-m" }),
    F.num("weight", "权重", { labelShort: "权", placeholder: "0", sizeClass: "field-s" }),
    F.chk("enabled", "启用", { labelShort: "启", sizeClass: "field-s" }),
  ])),

  fontConfig: C("src/config/fontConfig.ts", "字体：网站自定义字体配置", "字体配置", [
    F.chk("enable", "启用自定义字体"),
    F.txt("fontFamily", "字体名称"),
    F.txt("fontUrl", "字体URL"),
  ]),

  coverImageConfig: C("src/config/coverImageConfig.ts", "封面图：文章默认封面图片设置", "封面图", [
    F.chk("enable", "启用默认封面"),
    F.txt("defaultImage", "默认封面路径"),
  ]),

  analyticsConfig: C("src/config/analyticsConfig.ts", "统计分析：网站访问分析和统计配置", "统计分析", [
    F.chk("enable", "启用统计"),
    F.sel("provider", "统计服务", ["umami","plausible","google"]),
    F.txt("id", "站点ID"),
    F.txt("url", "统计服务URL"),
  ]),
};

window.FIREFLY_CONFIG_SCHEMA = FIREFLY_CONFIG_SCHEMA;
