// ============================================================
// Mizuki 平台配置 Schema
// ============================================================
const MIZUKI_CONFIG_SCHEMA = {
  siteConfig: C("src/config/siteConfig.ts", "网站核心配置：标题、域名、语言、主题色、功能开关等", "站点配置", [
    F.txt("title", "站点标题", { section: "basic", desc: "显示在浏览器标签页和页头的网站名称" }),
    F.txt("subtitle", "副标题", { section: "basic", desc: "标题下方的简短描述语" }),
    F.txt("siteURL", "站点URL", { section: "basic", desc: "网站的完整域名，以斜杠结尾" }),
    F.date("siteStartDate", "站点起始日期", { section: "basic", desc: "用于计算站点运行天数显示" }),
    F.sel("lang", "语言", ["zh_CN","en","ja"], { section: "basic", desc: "网站界面的默认显示语言" }),
    F.range("themeColor.hue", "主题色相(0-360)", 0, 360, { section: "theme", desc: "主题色在色环上的位置，0=红, 120=绿, 240=蓝" }),
    F.chk("themeColor.fixed", "固定主题色", { section: "theme", desc: "开启后将隐藏访客的主题色选择器" }),
    F.chk("featurePages.anime", "番剧页面", { section: "features", group: "featurePages" }),
    F.chk("featurePages.diary", "日记页面", { section: "features", group: "featurePages" }),
    F.chk("featurePages.friends", "友链页面", { section: "features", group: "featurePages" }),
    F.chk("featurePages.projects", "项目页面", { section: "features", group: "featurePages" }),
    F.chk("featurePages.skills", "技能页面", { section: "features", group: "featurePages" }),
    F.chk("featurePages.timeline", "时间线页面", { section: "features", group: "featurePages" }),
    F.chk("featurePages.albums", "相册页面", { section: "features", group: "featurePages" }),
    F.chk("featurePages.devices", "设备页面", { section: "features", group: "featurePages" }),
    F.chk("featurePages.aiTools", "AI工具页面", { section: "features", group: "featurePages" }),
    F.sel("navbarTitle.mode", "导航栏标题模式", ["text-icon","logo"], { section: "navbar" }),
    F.txt("navbarTitle.text", "导航栏标题文字", { section: "navbar" }),
    F.img("navbarTitle.icon", "导航栏图标路径", "public/images", { section: "navbar" }),
    F.img("navbarTitle.logo", "Logo图片路径", "public/images", { section: "navbar" }),
    F.sel("wallpaperMode.defaultMode", "壁纸模式", ["banner","fullscreen","none"], { section: "wallpaper" }),
    F.sel("wallpaperMode.showModeSwitchOnMobile", "模式切换显示", ["off","mobile","desktop","both"], { section: "wallpaper" }),
    F.sel("postListLayout.defaultMode", "文章列表布局", ["list","grid"], { section: "layout" }),
    F.chk("postListLayout.enable", "启用布局切换", { section: "layout" }),
    F.chk("postListLayout.allowSwitch", "允许用户切换", { section: "layout" }),
    F.chk("postListLayout.categoryBar.enable", "显示分类导航条", { section: "layout" }),
    F.chk("tagStyle.useNewStyle", "使用新标签样式", { section: "layout" }),
    F.chk("showCoverInContent", "文章内容显示封面", { section: "content" }),
    F.chk("showLastModified", "显示最后编辑时间", { section: "content" }),
    F.chk("generateOgImages", "生成OG图片", { section: "content" }),
    F.chk("toc.enable", "启用目录", { section: "content" }),
    F.chk("toc.mobileTop", "手机端TOC", { section: "content" }),
    F.chk("toc.desktopSidebar", "桌面端侧栏TOC", { section: "content" }),
    F.chk("toc.floating", "悬浮TOC", { section: "content" }),
    F.num("toc.depth", "目录深度", { min: 1, max: 6, section: "content" }),
    F.chk("toc.useJapaneseBadge", "日语假名标记", { section: "content" }),
    F.chk("pageProgressBar.enable", "页面进度条", { section: "ui" }),
    F.num("pageProgressBar.height", "进度条高度(px)", { min: 1, max: 10, section: "ui" }),
    F.num("pageProgressBar.duration", "动画时长(ms)", { min: 1000, section: "ui" }),
    F.chk("card.border", "卡片边框", { section: "ui" }),
    F.chk("card.followTheme", "卡片跟随主题色", { section: "ui" }),
    F.sel("imageOptimization.formats", "图片输出格式", ["webp","avif","both"], { section: "image" }),
    F.num("imageOptimization.quality", "图片质量", { min: 1, max: 100, section: "image" }),
    F.txt("bilibili.vmid", "Bilibili用户ID", { section: "integrations", desc: "B站用户UID，用于获取追番列表和视频数据" }),
    F.chk("bilibili.fetchOnDev", "开发环境获取B站数据", { section: "integrations" }),
    F.chk("bilibili.useWebp", "使用WebP格式", { section: "integrations" }),
    F.sel("anime.mode", "番剧模式", ["bangumi","local","bilibili"], { section: "integrations" }),
    F.txt("diaryApiUrl", "日记API地址", { section: "integrations" }),
    F.chk("thirdPartyAnalytics.enable", "第三方统计", { section: "integrations" }),
    F.txt("thirdPartyAnalytics.clarityId", "Clarity项目ID", { section: "integrations" }),
    F.chk("pageScaling.enable", "启用自动缩放", { section: "advanced" }),
    F.num("pageScaling.targetWidth", "目标宽度(px)", { min: 800, section: "advanced" }),
  ]),

  profileConfig: CA("src/config/profileConfig.ts", "个人信息：头像、昵称、个人简介和打字机效果", "个人资料", [
    F.img("avatar", "头像路径", "public/images", { desc: "public 目录下的相对路径" }),
    F.txt("name", "昵称", { desc: "显示在页面中的用户名称" }),
    F.area("bio", "个人简介", { desc: "简短的个人介绍，支持 HTML" }),
    F.chk("typewriter.enable", "打字机效果", { desc: "简介以打字机动画逐字显示" }),
    F.num("typewriter.speed", "打字速度(ms)", { min: 10 }),
  ], A("links", "社交链接", [
    F.txt("name", "名称", { placeholder: "GitHub" }),
    F.txt("url", "链接", { placeholder: "https://..." }),
    F.txt("icon", "图标", { placeholder: "fa7-brands:github" }),
  ])),

  navBarConfig: CA("src/config/navBarConfig.ts", "导航菜单配置：自定义网站顶部导航栏的链接和排序", "导航栏", [], A("links", "导航链接", [
    F.txt("name", "名称", { labelShort: "名", placeholder: "菜单名称", sizeClass: "field-m" }),
    F.txt("url", "链接", { labelShort: "链", placeholder: "/path/ 或 https://...", sizeClass: "field-m" }),
    F.txt("icon", "图标", { labelShort: "图", placeholder: "material-symbols:home", sizeClass: "field-m" }),
    F.chk("external", "外链", { labelShort: "外" }),
  ], { childrenKey: "children", linkPresets: ["Home","Archive","About","Friends","Anime","Diary","Albums","Projects","Skills","Timeline","AITools"] })),

  footerConfig: C("src/config/footerConfig.ts", "页脚配置：自定义网站底部信息和版权声明", "页脚", [
    F.chk("enable", "启用页脚HTML", { desc: "启用自定义页脚内容" }),
    F.area("customHtml", "自定义HTML", { desc: "自定义HTML代码，将显示在页面底部" }),
  ]),

  sidebarLayoutConfig: CAL("src/config/sidebarConfig.ts", "侧边栏布局：控制页面侧边栏的显示位置和内容", "侧边栏布局", [], [
    A("properties", "侧边栏组件", [
      F.sel("type", "组件类型", ["profile","announcement","music-sidebar","categories","tags","card-toc","site-stats","calendar"], { labelShort: "类", sizeClass: "field-m" }),
      F.sel("position", "位置", ["top","sticky"], { labelShort: "位", sizeClass: "field-l" }),
      F.txt("class", "CSS类", { labelShort: "样", placeholder: "onload-animation", sizeClass: "field-m" }),
      F.num("animationDelay", "延迟(ms)", { labelShort: "延", sizeClass: "field-n" }),
    ]),
  ]),

  commentConfig: C("src/config/commentConfig.ts", "评论系统：配置 Twikoo 或 Giscus 评论服务", "评论系统", [
    F.chk("enable", "启用评论", { desc: "开启后文章页面底部将显示评论区" }),
    F.sel("system", "评论系统", ["twikoo","giscus"], { desc: "选择评论后端：Twikoo 或 Giscus" }),
    F.txt("twikoo.envId", "Twikoo环境ID"),
    F.txt("twikoo.lang", "Twikoo语言"),
    F.txt("giscus.repo", "Giscus仓库"),
    F.txt("giscus.repoId", "Giscus仓库ID"),
    F.txt("giscus.category", "Giscus分类"),
    F.txt("giscus.categoryId", "Giscus分类ID"),
    F.txt("giscus.mapping", "映射方式"),
    F.txt("giscus.theme", "Giscus主题"),
  ]),

  announcementConfig: C("src/config/announcementConfig.ts", "公告栏：网站顶部公告横幅的内容和链接", "公告栏", [
    F.txt("title", "公告标题"),
    F.area("content", "公告内容"),
    F.chk("closable", "允许关闭"),
    F.chk("link.enable", "启用链接"),
    F.txt("link.text", "链接文字"),
    F.txt("link.url", "链接URL"),
    F.chk("link.external", "外部链接"),
  ]),

  musicPlayerConfig: C("src/config/musicConfig.ts", "音乐播放器：背景音乐播放、歌单和播放模式", "音乐播放器", [
    F.chk("enable", "启用音乐", { desc: "开启站点背景音乐播放功能" }),
    F.chk("showInNavbar", "导航栏显示", { desc: "在导航栏中显示音乐入口图标" }),
    F.chk("showFloatingPlayer", "悬浮播放器", { desc: "在页面右下角显示音乐控制按钮" }),
    F.sel("floatingEntryMode", "悬浮入口模式", ["default","fab"]),
    F.sel("mode", "播放器模式", ["local","meting"]),
    F.txt("id", "歌单ID"),
    F.sel("server", "音乐源", ["netease","tencent","kugou","xiami","baidu"]),
    F.sel("type", "播单类型", ["playlist","album","song"]),
  ]),

  licenseConfig: C("src/config/licenseConfig.ts", "许可证：网站内容许可协议和版权声明", "许可证", [
    F.chk("enable", "启用许可证"),
    F.txt("name", "许可证名称"),
    F.txt("url", "许可证URL"),
  ]),

  pioConfig: C("src/config/pioConfig.ts", "看板娘：网页右下角Live2D角色的位置和行为", "看板娘", [
    F.chk("enable", "启用看板娘", { desc: "在页面角落显示Live2D动漫角色" }),
    F.sel("position", "位置", ["left","right"]),
    F.num("width", "宽度(px)", { min: 100 }),
    F.num("height", "高度(px)", { min: 100 }),
    F.sel("mode", "模式", ["draggable","static","fixed"]),
    F.chk("hiddenOnMobile", "移动端隐藏"),
    F.chk("hideAboutMenu", "隐藏关于菜单"),
    F.txt("dialog.welcome", "欢迎词"),
    F.txt("dialog.close", "关闭提示"),
    F.txt("dialog.link", "关于链接"),
  ]),

  fullscreenWallpaperConfig: C("src/config/backgroundWallpaper.ts", "全屏壁纸：背景图片轮播、模糊和不透明度效果", "全屏壁纸", [
    F.chk("enable", "启用壁纸", { desc: "开启全屏背景壁纸效果" }),
    F.sel("mode", "壁纸模式", ["banner","fullscreen","overlay","none"], { desc: "壁纸的显示模式" }),
    F.chk("switchable", "用户可切换"),
    F.chk("playerEnable", "启用视频播放器"),
    F.sel("position", "图片位置", ["top","center","bottom"], { desc: "背景图片的对齐方式" }),
    F.chk("carousel.enable", "启用轮播"),
    F.num("carousel.interval", "轮播间隔(s)", { min: 1 }),
    F.num("zIndex", "层级"),
    F.num("opacity", "不透明度(0-1)", { min: 0, max: 1, step: 0.05 }),
    F.num("blur", "模糊(px)", { min: 0 }),
    F.num("common.dimOpacity", "背景遮罩不透明度", { min: 0, max: 1, step: 0.05 }),
    F.sel("common.playerMode", "视频播放模式", ["random","sequential","single"]),
    F.chk("common.homeText.enable", "启用主页文字"),
    F.chk("common.homeText.switchable", "文字可切换"),
    F.txt("common.homeText.title", "主页标题"),
    F.txt("common.homeText.titleSize", "标题字号", { placeholder: "3.8rem" }),
    F.txt("common.homeText.subtitleSize", "副标题字号", { placeholder: "1.5rem" }),
    F.chk("common.homeText.typewriter.enable", "打字机效果"),
    F.num("common.homeText.typewriter.speed", "打字速度(ms)", { min: 10 }),
    F.num("common.homeText.typewriter.deleteSpeed", "删除速度(ms)", { min: 10 }),
    F.num("common.homeText.typewriter.pauseTime", "暂停时间(ms)", { min: 100 }),
    F.sel("common.navbar.transparentMode", "导航栏透明模式", ["solid","semi","transparent"]),
    F.chk("common.navbar.enableBlur", "导航栏模糊"),
    F.num("common.navbar.blur", "导航栏模糊(px)", { min: 0 }),
    F.chk("common.waves.enable.desktop", "桌面端波浪"),
    F.chk("common.waves.enable.mobile", "移动端波浪"),
    F.chk("common.waves.switchable", "波浪可切换"),
    F.chk("common.gradient.enable.desktop", "桌面端渐变"),
    F.chk("common.gradient.enable.mobile", "移动端渐变"),
    F.txt("common.gradient.height", "渐变高度", { placeholder: "10%" }),
    F.chk("common.gradient.switchable", "渐变可切换"),
    F.chk("common.carousel.enable", "通用轮播"),
    F.num("common.carousel.interval", "通用轮播间隔(ms)", { min: 1000, step: 500 }),
    F.sel("common.carousel.transitionEffect", "过渡效果", ["fade","zoom","slide"]),
    F.chk("common.carousel.switchable", "轮播可切换"),
    F.txt("banner.position", "Banner位置", { placeholder: "0% 20%" }),
    F.num("overlay.zIndex", "覆盖层层级"),
    F.num("overlay.opacity", "覆盖层不透明度", { min: 0, max: 1, step: 0.05 }),
    F.num("overlay.blur", "覆盖层模糊(px)", { min: 0 }),
    F.num("overlay.cardOpacity", "卡片不透明度", { min: 0, max: 1, step: 0.05 }),
    F.chk("overlay.switchable.opacity", "可切换不透明度"),
    F.chk("overlay.switchable.blur", "可切换模糊"),
    F.chk("overlay.switchable.cardOpacity", "可切换卡片不透明度"),
    F.chk("fullscreen.switchable.opacity", "全屏可切换不透明度"),
    F.chk("fullscreen.switchable.blur", "全屏可切换模糊"),
    F.txt("fullscreen.position", "全屏位置", { placeholder: "center" }),
  ]),

  sakuraConfig: C("src/config/effectsConfig.ts", "樱花特效：飘落花瓣的数量、大小和透明度", "樱花特效", [
    F.chk("enable", "启用樱花", { desc: "开启页面飘落樱花花瓣动画特效" }),
    F.chk("switchable", "可切换"),
    F.num("sakuraNum", "樱花数量", { min: 1 }),
    F.num("limitTimes", "限制次数(-1无限)"),
    F.num("size.min", "最小尺寸倍数", { min: 0, step: 0.1 }),
    F.num("size.max", "最大尺寸倍数", { min: 0, step: 0.1 }),
    F.num("opacity.min", "最小不透明度", { min: 0, max: 1, step: 0.05 }),
    F.num("opacity.max", "最大不透明度", { min: 0, max: 1, step: 0.05 }),
    F.num("zIndex", "层级"),
  ]),

  expressiveCodeConfig: C("src/config/expressiveCodeConfig.ts", "代码块样式：文章中代码高亮的主题和显示效果", "代码块样式", [
    F.sel("theme", "代码主题", ["github-dark","github-light","monokai","dracula"]),
    F.chk("hideDuringThemeTransition", "主题切换时隐藏"),
  ]),

  permalinkConfig: C("src/config/permalinkConfig.ts", "固定链接：文章URL的生成格式和规则", "固定链接", [
    F.chk("enable", "启用固定链接"),
    F.txt("format", "链接格式"),
  ]),

  randomPostsConfig: C("src/config/randomPostsConfig.ts", "随机文章：页面随机推荐文章的显示数量和规则", "随机文章", [
    F.chk("enable", "启用随机文章"),
    F.num("maxCount", "最大数量", { min: 1 }),
  ]),

  relatedPostsConfig: C("src/config/relatedPostsConfig.ts", "相关文章：文章底部关联推荐的匹配算法和权重", "相关文章", [
    F.chk("enable", "启用相关文章"),
    F.num("maxCount", "最大数量", { min: 1 }),
    F.num("weights.tagSimilarity", "标签相似度权重", { min: 0, step: 0.1 }),
    F.num("weights.titleSimilarity", "标题相似度权重", { min: 0, step: 0.1 }),
    F.num("weights.descriptionSimilarity", "描述相似度权重", { min: 0, step: 0.1 }),
    F.num("weights.categoryMatch", "分类匹配权重", { min: 0, step: 0.1 }),
    F.num("weights.freshness", "新鲜度权重", { min: 0, step: 0.1 }),
    F.num("freshnessHalfLife", "新鲜度半衰期(天)", { min: 1 }),
  ]),

  shareConfig: C("src/config/shareConfig.ts", "分享功能：控制文章社交媒体分享按钮的显示", "分享功能", [
    F.chk("enable", "启用分享"),
  ]),
};

window.MIZUKI_CONFIG_SCHEMA = MIZUKI_CONFIG_SCHEMA;
